config/routes.rb
Costpad::Application.routes.draw do

  resources :accounts

  match '/about', to: 'pages#about'
  match '/signup', to: 'accounts#new'

  root :to => 'pages#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { |account| account.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  def new
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
	@account = Account.find(params[:id])	
  end

  def new
  	@account = Account.new
  end

  def create
    @account = Account.new(params[:account])
    if @account.save
      # Handle a successful save.
    else
      render 'new'
    end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/accounts/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="six columns">
  
    <%= form_for(@account) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "button" %>
    <% end %>
  
</div>

app/views/accounts/show.html.erb
<% provide(:title, @account.name) %>

<%= @account.name %>, <%= @account.email %>

app/views/layouts/_sidebar_home.html.erb
   
    <aside class="three columns">

      <h4>use it anywhere</h4>
      
      <div class="panel">

        <p>Use Costpad for all your cost estimates and quotes, your data is available 24/7 and easily managed on any web device, including your phone.</p>
  
      </div>

      <h4>get started</h4>

      <ul class="side-nav">
        <li><%= link_to "sign up", signup_path, class: "button" %></li>
        <li><%= link_to "login", '#', class: "button" %></li>
      </ul>


    </aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title>Costpad estimating app | <%= yield(:title) %></title>
  
	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
	
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
    <!-- Navigation -->
  <div class="row">
    <div class="twelve columns">
      <ul class="nav-bar">
        <li class="name"><%= link_to "Costpad", root_path %></li>
        <li><%= link_to "about", about_path %></li>
        <li><%= link_to "sign up", signup_path %></li>
        <li><a href="#">Link 4</a></li>
      </ul>
    </div>
  </div>
   <!-- End Navigation -->
 
  <!-- Main Page Content and Sidebar -->
 
  <div class="row">
 
    <!-- Main Blog Content -->
    <div class="nine columns" role="content">
 
      <section>

      
      <%= yield %>
 

 
      </section>
 
    </div>
 
    <!-- End Main Content -->
 
 
    <!-- Sidebar -->
 
    <%= render 'layouts/sidebar_home' %>
 
    <!-- End Sidebar -->
  </div>
 
  <!-- End Main Content and Sidebar -->
 
    <!-- Footer -->
 
  <footer class="row">
    <div class="twelve columns"><hr />
      <div class="row">
 
        <div class="six columns">
          <p>&copy; Copyright Costpad.com.</p>
        </div>
 
        <div class="six columns">
          <ul class="link-list right">
            <li><a href="#">Link 1</a></li>
            <li><a href="#">Link 2</a></li>
            <li><a href="#">Link 3</a></li>
            <li><a href="#">Link 4</a></li>
          </ul>
        </div>
 
      </div>
    </div>
  </footer>
 
    <!-- End Footer -->
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'about') %>
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
<% provide(:title, 'Home') %>

<h1>Costpad</h1>
<p><b>Costpad estimating app</b> lets you estimate the cost of just about anything ... a trade services quote, a recipe (or a whole menu), maybe even the cost of planting a crop, you decide.</p>

<p><b>Create</b> and <b>save</b> a database of your cost items for later reference, or re-use the data in other projects or applications.</p>

<p><b>Build</b> your project estimate, <b>save</b>, <b>send</b>, or <b>download</b> it.</p>

<h2>Step 1</h2>

<p>Open an account, it's free, but we need a unique ID to store and secure your stuff.</p>

<h2>Step 2</h2>

<p>Create items to use in your costing or estimate.</p>

<h2>Step 3</h2>

<p>Build your estimate and save it, download it, or send it via email direct from the application.</p>

<p>You can keep copies of your cost items and finished project estimates on our secure Cloud storage platform.</p>